### ISSUE TITLE
Sync Issues, with Mac Device

### ISSUE THREAD

**Issue by richardsillito** [jimboca/harmonyhub-polyglot#14] opened 2018-02-03 02:21 UTC
Hi jimboca, I manged to reproduce the error when it fails to sync with a MAC Device. Here is the error from the logs... I'll leave it in a broken state in case you need me to look at anything... 

Version Info...
2018-02-02 19:11:52,746 INFO     Updating Driver harmonyctrl - GV1: 2.1
2018-02-02 19:11:52,747 INFO     Updating Driver harmonyctrl - GV2: 6

2018-02-02 19:12:09,481 ERROR    Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/dude/.polyglot/nodeservers/HarmonyHub/harmony_hub_nodes/HarmonyController.py", line 411, in _build_profile
    config_data = write_profile(LOGGER,self.hubs)
  File "/home/dude/.polyglot/nodeservers/HarmonyHub/write_profile.py", line 189, in write_profile
    ay = yaml.load(a.replace('\\',''))
  File "/home/dude/.local/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/home/dude/.local/lib/python3.5/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/home/dude/.local/lib/python3.5/site-packages/yaml/composer.py", line 35, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/home/dude/.local/lib/python3.5/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/dude/.local/lib/python3.5/site-packages/yaml/parser.py", line 143, in parse_implicit_document_start
    StreamEndToken):
  File "/home/dude/.local/lib/python3.5/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/dude/.local/lib/python3.5/site-packages/yaml/scanner.py", line 252, in fetch_more_tokens
    return self.fetch_plain()
  File "/home/dude/.local/lib/python3.5/site-packages/yaml/scanner.py", line 676, in fetch_plain
    self.tokens.append(self.scan_plain())
  File "/home/dude/.local/lib/python3.5/site-packages/yaml/scanner.py", line 1299, in scan_plain
    "Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.")
yaml.scanner.ScannerError: while scanning a plain scalar
  in "<unicode string>", line 1, column 17:
    {"command":""","type":"IRCommand","deviceId":"51 ... 
                    ^
found unexpected ':'
  in "<unicode string>", line 1, column 22:
    {"command":""","type":"IRCommand","deviceId":"51860805"}
                         ^
Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dude/.polyglot/nodeservers/HarmonyHub/harmony_hub_nodes/HarmonyController.py", line 253, in _discover
    if self._build_profile():
  File "/home/dude/.polyglot/nodeservers/HarmonyHub/harmony_hub_nodes/HarmonyController.py", line 413, in _build_profile
    self.l_error('build_profile','write_profile failed: {}'.format(err), exc_info=True)
TypeError: l_error() got an unexpected keyword argument 'exc_info'
2018-02-02 19:12:09,482 WARNING  /usr/lib/python3.5/threading.py:947: ResourceWarning: unclosed file <_io.TextIOWrapper name='profile/nls/en_us.txt' mode='w' encoding='UTF-8'>
2018-02-02 19:12:09,482 WARNING  /usr/lib/python3.5/threading.py:947: ResourceWarning: unclosed file <_io.TextIOWrapper name='profile/nodedef/custom.xml' mode='w' encoding='UTF-8'>
2018-02-02 19:12:09,482 WARNING  /usr/lib/python3.5/threading.py:947: ResourceWarning: unclosed file <_io.TextIOWrapper name='profile/editor/custom.xml' mode='w' encoding='UTF-8'>
2018-02-02 19:12:12,734 DEBUG    HarmonyController:shortPoll: discover thread is done...

**Comment by richardsillito** [comment] 2018-02-03 02:28
Hey looking at this, it looks like a quote issues

{"command":""","type":"IRCommand","deviceId":"51860805"}

The mac device basically creates a device button for every key on the keyboard, when it load the " button your getting a quotation mismatch

**Comment by jimboca** [comment] 2018-02-03 03:24
Yes, nice catch, that won't be to hard to fix, but I'll have to figure out a way to simulate the error to verify on my side.

**Comment by jimboca** [comment] 2018-02-03 03:26
BTW, you entered this for the old v1 Polyglot, are you still using this one or the V2?

**Comment by richardsillito** [comment] 2018-02-03 14:54
Opps sorry about that, yes I am on v2. Was watching tv while making the report, clearly I cant multitask... You can just add a Mac to your harmony hub without actually having a mac. Then to reproduce the problem I removed the nodeserver from the isy and delete the nodeserver directory from the polyglot server, then re-install. Also if you need, I could spin you up a windows 10 desktop and a linux polyglot server and you could test here.

**Comment by richardsillito** [comment] 2018-02-03 14:56
Also I'm willing to help out with the testing...

**Comment by jimboca** [comment] 2018-02-03 16:38
No problem, I've added a Mac to my hub and will test.

**Comment by richardsillito** [comment] 2018-02-03 17:06
Cool... Can you let me know when you have reproduced the problem, as I'm leaving my system broken just in case you need it.

**Comment by jimboca** [comment] 2018-02-03 17:12
Thanks, I have reproduced it and working on a fix.

**Comment by jimboca** [comment] 2018-02-03 17:38
Version 2.1.7 released which fixes this issue.  It was actually caused by a bad hack that avoided parsing issues with / in action names.

(This issue was not fixed in this version, it was fixed in the Polglot V2 version https://github.com/jimboca/udi-harmony-poly

**Closed as completed by jimboca** 2018-02-03 17:38 UTC

**Comment by richardsillito** [comment] 2018-02-04 00:03
Just tested it and everything is work wonderfully!!! Thanks again for you help, this is such a nice addon to the ISY system... Keep up the good work and if your ever in Calgary Canada, look me up, I owe a beer or 2...

**Comment by jimboca** [comment] 2018-02-04 00:53
Awesome, thanks for confirming, and the drink offer
